### ISSUE TITLE
batch client blocks

### ISSUE THREAD

**Issue by shmish111** [riemann/riemann-clojure-client#23]
``` clj
(def client (r/batch-client (r/tcp-client {}) 2))
(r/send-event client {:service "my-service" :host "my-host"})
```

This code does not return unless I `flush` the client manually on another thread or `send-event` again on another thread (thus making the `batch-client` buffer full so it flushes itself).

How do I use `batch-client`?

**Comment by aphyr** [comment]
Gosh, sounds like a bug!
On Sep 22, 2016 4:50 AM, David Smith <notifications@github.com> wrote:(def client (r/batch-client (r/tcp-client {}) 2))
(r/send-event client {:service "my-service" :host "my-host"})

This code does not return unless I flush the client manually on another thread or send-event again on another thread (thus making the batch-client buffer full so it flushes itself).

How do I use batch-client?

**Comment by shmish111** [comment]
OK, I thought perhaps I was using `batch-client` incorrectly.

**Comment by aphyr** [comment]
Now that I think about it, this miiiight have been done because I didn't want to introduce an additional timer/flusher thread in the java client to ensure batches were flushed every few milliseconds; so we assumed the number of writer threads would be larger than the batch size. It might be worth adding that thread (and appropriate lifecycle handling) to periodically flush events.

**Comment by jamtur01** [comment]
Please re-open if this remains an issue and needs a fix.
